### ISSUE TITLE
运行Trojan节点报错

### ISSUE THREAD

**Issue by haig233** [long2k3pro/XrayR#36]
配置文件
```
Log:
  Level: debug
  AccessPath: ./access.log
  ErrorPath: ./error.log
DnsConfigPath: ./dns.json
Nodes:
  -
    PanelType: "SSpanel"
    ApiConfig:
      ApiHost: "https://aaaaaaaaaaaaa.co/"
      ApiKey: "ddddddddd"
      NodeID: 1
      NodeType: Trojan
      Timeout: 30
      EnableVless: false
      EnableXTLS: false
    ControllerConfig:
      ListenIP: 0.0.0.0
      UpdatePeriodic: 60
      EnableDNS: false
      CertConfig:
        CertMode: dns
        CertDomain: "usa1.abc"
        Provider: cloudflare
        Email: ssssssssssssss@gmail.com
        DNSEnv: 
          CF_DNS_API_TOKEN: xxxxxxxxxxxxxxxxxxx
```

SSpanel使用Trojan TCP节点，gz.aaa.com;port=443|host=gz.aaa.com

启动后报错
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/long2k3pro/XrayR/api/sspanel.(*APIClient).ParseTrojanNodeResponse(0xc000235050, 0xc000238a00)
        github.com/long2k3pro/XrayR/api/sspanel/sspanel.go:633 +0x592
github.com/long2k3pro/XrayR/api/sspanel.(*APIClient).GetNodeInfo(0xc000235050)
        github.com/long2k3pro/XrayR/api/sspanel/sspanel.go:193 +0x4f3
github.com/long2k3pro/XrayR/service/controller.(*Controller).Start(0xc0001474a0)
        github.com/long2k3pro/XrayR/service/controller/controller.go:46 +0xf2
github.com/long2k3pro/XrayR/panel.(*Panel).Start(0xc000119dc0)
        github.com/long2k3pro/XrayR/panel/panel.go:193 +0x59a
main.main()
        github.com/long2k3pro/XrayR/main/main.go:92 +0x1ed

```
